"""
Application-wide constants.

This module contains shared constants used throughout the system,
including part categories, validation rules, cache settings, and thresholds.
"""

# Part Categories
PART_CATEGORY_BRAKE = "BRAKE"
PART_CATEGORY_ENGINE = "ENGINE"
PART_CATEGORY_FILTER = "FILTER"
PART_CATEGORY_FLUID = "FLUID"
PART_CATEGORY_ELECTRICAL = "ELECTRICAL"
PART_CATEGORY_SUSPENSION = "SUSPENSION"
PART_CATEGORY_TRANSMISSION = "TRANSMISSION"
PART_CATEGORY_COOLING = "COOLING"
PART_CATEGORY_EXHAUST = "EXHAUST"
PART_CATEGORY_OTHER = "OTHER"

ALL_PART_CATEGORIES = [
    PART_CATEGORY_BRAKE,
    PART_CATEGORY_ENGINE,
    PART_CATEGORY_FILTER,
    PART_CATEGORY_FLUID,
    PART_CATEGORY_ELECTRICAL,
    PART_CATEGORY_SUSPENSION,
    PART_CATEGORY_TRANSMISSION,
    PART_CATEGORY_COOLING,
    PART_CATEGORY_EXHAUST,
    PART_CATEGORY_OTHER,
]


# Seasons (Indian context)
SEASON_SUMMER = "SUMMER"
SEASON_MONSOON = "MONSOON"
SEASON_SPRING = "SPRING"
SEASON_WINTER = "WINTER"

ALL_SEASONS = [
    SEASON_SUMMER,
    SEASON_MONSOON,
    SEASON_SPRING,
    SEASON_WINTER,
]

# Season month mapping (0-indexed, where 0 = January)
SEASON_MONTHS = {
    SEASON_SUMMER: [2, 3, 4],      # March, April, May (0-indexed: 2, 3, 4)
    SEASON_MONSOON: [5, 6, 7, 8],   # June, July, August, September
    SEASON_SPRING: [9, 10],         # October, November
    SEASON_WINTER: [11, 0, 1],      # December, January, February
}


# Terrain Types
TERRAIN_URBAN = "URBAN"
TERRAIN_HIGHWAY = "HIGHWAY"
TERRAIN_MIXED = "MIXED"
TERRAIN_OFF_ROAD = "OFF_ROAD"
TERRAIN_HILLY = "HILLY"

ALL_TERRAIN_TYPES = [
    TERRAIN_URBAN,
    TERRAIN_HIGHWAY,
    TERRAIN_MIXED,
    TERRAIN_OFF_ROAD,
    TERRAIN_HILLY,
]


# Model Configuration
DEFAULT_CONFIDENCE_THRESHOLD = 0.80  # 80%
MIN_CONFIDENCE_THRESHOLD = 0.50      # 50%
MAX_CONFIDENCE_THRESHOLD = 0.95      # 95%

MAX_RECOMMENDATIONS = 10
MIN_RECOMMENDATIONS = 1


# Validation Thresholds
MIN_ODOMETER = 0.0
MAX_ODOMETER = 9999999.0  # 10 million km

MIN_VEHICLE_AGE_DAYS = 0
MAX_VEHICLE_AGE_DAYS = 36500  # ~100 years

MIN_SERVICE_INTERVAL_DAYS = 1
MAX_SERVICE_INTERVAL_DAYS = 3650  # ~10 years


# EMA Configuration
DEFAULT_EMA_PERIODS = 6
MIN_EMA_PERIODS = 2
MAX_EMA_PERIODS = 24

MIN_SERVICES_FOR_EMA = 2


# Cache TTL (Time To Live) in seconds
CACHE_TTL_RECOMMENDATION = 3600      # 1 hour
CACHE_TTL_VEHICLE = 1800             # 30 minutes
CACHE_TTL_SERVICE_HISTORY = 1800     # 30 minutes
CACHE_TTL_MODEL = 86400              # 24 hours
CACHE_TTL_EMA = 3600                 # 1 hour
CACHE_TTL_PREDICTION = 1800          # 30 minutes


# API Configuration
API_MAX_REQUEST_SIZE = 10485760      # 10 MB
API_TIMEOUT_SECONDS = 30
API_MAX_CONCURRENT_REQUESTS = 500


# Database Configuration
DB_CONNECTION_TIMEOUT = 30
DB_POOL_SIZE = 20
DB_MAX_OVERFLOW = 40
DB_POOL_RECYCLE = 3600


# Recommendation Status
REC_STATUS_PENDING = "PENDING"
REC_STATUS_ACCEPTED = "ACCEPTED"
REC_STATUS_REJECTED = "REJECTED"
REC_STATUS_IGNORED = "IGNORED"
REC_STATUS_EXPIRED = "EXPIRED"

ALL_REC_STATUSES = [
    REC_STATUS_PENDING,
    REC_STATUS_ACCEPTED,
    REC_STATUS_REJECTED,
    REC_STATUS_IGNORED,
    REC_STATUS_EXPIRED,
]


# Feedback Action Types
FEEDBACK_ACTION_ACCEPTED = "ACCEPTED"
FEEDBACK_ACTION_REJECTED = "REJECTED"
FEEDBACK_ACTION_IGNORED = "IGNORED"

ALL_FEEDBACK_ACTIONS = [
    FEEDBACK_ACTION_ACCEPTED,
    FEEDBACK_ACTION_REJECTED,
    FEEDBACK_ACTION_IGNORED,
]


# Model Training
TRAIN_MIN_SAMPLES = 100
TRAIN_TEST_SPLIT_RATIO = 0.8  # 80% train, 20% test
MIN_TRAINING_SET_SIZE = 1000
MIN_TEST_SET_SIZE = 100


# Validation Metrics Thresholds
MIN_PRECISION_THRESHOLD = 0.70  # 70%
MIN_RECALL_THRESHOLD = 0.70     # 70%
MIN_F1_THRESHOLD = 0.70         # 70%

TARGET_PRECISION_THRESHOLD = 0.80  # 80%
TARGET_RECALL_THRESHOLD = 0.80    # 80%
TARGET_F1_THRESHOLD = 0.80         # 80%


# Model Drift Detection
DRIFT_WARNING_THRESHOLD = 0.03   # 3% drop
DRIFT_CRITICAL_THRESHOLD = 0.05  # 5% drop


# A/B Testing
AB_TEST_SPLIT_RATIO_DEFAULT = 0.2  # 20% to new model
AB_TEST_MIN_DURATION_DAYS = 7
AB_TEST_MIN_SAMPLES = 1000


# Date Formats
DATE_FORMAT_ISO = "%Y-%m-%d"
DATETIME_FORMAT_ISO = "%Y-%m-%dT%H:%M:%S"
DATETIME_FORMAT_ISO_WITH_TZ = "%Y-%m-%dT%H:%M:%S%z"


# Regular Expression Patterns
PATTERN_VEHICLE_ID = r'^[A-Za-z0-9]{6,20}$'
PATTERN_PART_CODE = r'^[A-Z]{2}\d{3}$'
PATTERN_EMAIL = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
PATTERN_PHONE = r'^(\+91)?[6-9]\d{9}$'


# Error Codes
ERROR_CODE_VEHICLE_NOT_FOUND = "VEHICLE_NOT_FOUND"
ERROR_CODE_INVALID_INPUT = "INVALID_INPUT"
ERROR_CODE_MODEL_ERROR = "MODEL_ERROR"
ERROR_CODE_DATABASE_ERROR = "DATABASE_ERROR"
ERROR_CODE_CACHE_ERROR = "CACHE_ERROR"
ERROR_CODE_VALIDATION_ERROR = "VALIDATION_ERROR"
ERROR_CODE_PREDICTION_ERROR = "PREDICTION_ERROR"


# Logging
LOG_LEVEL_DEBUG = "DEBUG"
LOG_LEVEL_INFO = "INFO"
LOG_LEVEL_WARNING = "WARNING"
LOG_LEVEL_ERROR = "ERROR"
LOG_LEVEL_CRITICAL = "CRITICAL"

ALL_LOG_LEVELS = [
    LOG_LEVEL_DEBUG,
    LOG_LEVEL_INFO,
    LOG_LEVEL_WARNING,
    LOG_LEVEL_ERROR,
    LOG_LEVEL_CRITICAL,
]

